#!/usr/bin/env bash
# Build the Flutter Web GameNode and copy the output into assets/web_node/
# so the iPad shelf server can bundle and serve it.
#
# Usage: bash scripts/build_web_node.sh
# Run this before `flutter build` or `flutter run` for the iPad target whenever
# the GameNode web UI changes.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."

FLUTTER_BIN="${FLUTTER_BIN:-$(command -v flutter || echo "")}"
if [ -z "$FLUTTER_BIN" ] && [ -x "$HOME/fvm/versions/stable/bin/flutter" ]; then
  FLUTTER_BIN="$HOME/fvm/versions/stable/bin/flutter"
fi
if [ -z "$FLUTTER_BIN" ]; then
  echo "✗ flutter not found in PATH. Set FLUTTER_BIN or install Flutter." >&2
  exit 1
fi

cd "$ROOT"

echo "▶ Clearing stale web_node assets and pubspec entries..."
rm -rf assets/web_node
# Empty the asset list between sentinels so the web build doesn't
# recursively bundle its own output.
python3 - <<'PYEOF'
with open('pubspec.yaml', 'r', encoding='utf-8') as f:
    text = f.read()
begin = '# <web_node_begin>'
end = '# <web_node_end>'
if begin in text and end in text:
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    new_text = head + begin + ' (auto-regenerated by scripts/build_web_node.sh)\n    ' + end + tail
    with open('pubspec.yaml', 'w', encoding='utf-8') as f:
        f.write(new_text)
PYEOF

echo "▶ Building Flutter Web GameNode with $FLUTTER_BIN..."
"$FLUTTER_BIN" build web --release \
  --dart-define=BOARD_GO_ROLE=gamenode

echo "▶ Copying to assets/web_node/..."
rm -rf assets/web_node
mkdir -p assets/web_node
cp -R build/web/. assets/web_node/

echo "▶ Regenerating pubspec.yaml asset entries for web_node subdirectories..."
python3 - <<'PYEOF'
import os

root = 'assets/web_node'
dirs = []
for dp, _dn, fn in os.walk(root):
    if fn:
        dirs.append(dp.replace(os.sep, '/') + '/')
dirs.sort()

with open('pubspec.yaml', 'r', encoding='utf-8') as f:
    text = f.read()

begin = '# <web_node_begin>'
end = '# <web_node_end>'
if begin not in text or end not in text:
    raise SystemExit('pubspec.yaml is missing web_node sentinel markers.')

head, rest = text.split(begin, 1)
_, tail = rest.split(end, 1)

# Preserve indentation of the begin marker (4 spaces under "assets:")
indent = '    '
lines = [f'{indent}{begin} (auto-regenerated by scripts/build_web_node.sh)']
for d in dirs:
    lines.append(f'{indent}- {d}')
lines.append(f'{indent}{end}')

# head ends with the indent before <web_node_begin>, so strip trailing whitespace
head = head.rstrip(' ')
new_text = head + '\n'.join(lines) + tail
with open('pubspec.yaml', 'w', encoding='utf-8') as f:
    f.write(new_text)
print(f'  Registered {len(dirs)} directories under assets/web_node/')
PYEOF

echo "✓ Done — assets/web_node/ is ready and pubspec updated."
echo "  Now run 'flutter run -d <ipad-device-id>' to bundle and deploy."
